python "/vdj_recovery/findvdj.py" TRA '/mnt/results/TRA/'
python "/vdj_recovery/findvdj.py" TRB '/mnt/results/TRB/'
python "/vdj_recovery/findvdj.py" TRD '/mnt/results/TRD/'
python "/vdj_recovery/findvdj.py" TRG '/mnt/results/TRG/'
python "/vdj_recovery/findvdj.py" IGK '/mnt/results/IGK/'
python "/vdj_recovery/findvdj.py" IGL '/mnt/results/IGL/'
python "/vdj_recovery/findvdj.py" IGH '/mnt/results/IGH/'
python "/vdj_recovery/findvdj.py" TRA '/mnt/results/TRA_UM/'
python "/vdj_recovery/findvdj.py" TRB '/mnt/results/TRB_UM/'
python "/vdj_recovery/findvdj.py" TRD '/mnt/results/TRD_UM/'
python "/vdj_recovery/findvdj.py" TRG '/mnt/results/TRG_UM/'
python "/vdj_recovery/findvdj.py" IGK '/mnt/results/IGK_UM/'
python "/vdj_recovery/findvdj.py" IGL '/mnt/results/IGL_UM/'
python "/vdj_recovery/findvdj.py" IGH '/mnt/results/IGH_UM/'


python "/vdj_recovery/vdjrecord_header.py" '/mnt/results/'
