python "/vdj_recovery/findvdj.py" TRA '/mnt/results/TRA/'
python "/vdj_recovery/findvdj.py" TRB '/mnt/results/TRB/'
python "/vdj_recovery/findvdj.py" TRD '/mnt/results/TRD/'
python "/vdj_recovery/findvdj.py" TRG '/mnt/results/TRG/'
python "/vdj_recovery/findvdj.py" IGK '/mnt/results/IGK/'
python "/vdj_recovery/findvdj.py" IGL '/mnt/results/IGL/'
python "/vdj_recovery/findvdj.py" IGH '/mnt/results/IGH/'
python "/vdj_recovery/findvdj.py" TRA_UM '/mnt/results/TRA_UM/'
python "/vdj_recovery/findvdj.py" TRB_UM '/mnt/results/TRB_UM/'
python "/vdj_recovery/findvdj.py" TRD_UM '/mnt/results/TRD_UM/'
python "/vdj_recovery/findvdj.py" TRG_UM '/mnt/results/TRG_UM/'
python "/vdj_recovery/findvdj.py" IGK_UM '/mnt/results/IGK_UM/'
python "/vdj_recovery/findvdj.py" IGL_UM '/mnt/results/IGL_UM/'
python "/vdj_recovery/findvdj.py" IGH_UM '/mnt/results/IGH_UM/'


python "/vdj_recovery/vdjrecord_header.py" '/mnt/results/'
